<?xml version="1.0"?>
<robot name="wheelchair_base" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ****************** ROBOT CONSTANTS *******************************  -->
  <!-- Define the size of the robot's main chassis in meters -->
  <xacro:property name="base_width" value="0.6" />
  <xacro:property name="base_length" value="1.18" />
  <xacro:property name="base_height" value="0.65" />

  <!-- Define the shape of the robot's two back wheels in meters -->
  <xacro:property name="wheel_radius" value="0.27" />
  <xacro:property name="wheel_width" value="0.05" />

  <xacro:property name="front_wheel_radius" value="0.12" />

  <!-- x-axis points forward, y-axis points to left, z-axis points upwards -->
  <!-- Define the gap between the wheel and chassis along y-axis in meters -->
  <xacro:property name="wheel_ygap" value="${wheel_width/2}" />
  <!-- Position the wheels along the z-axis -->
  <xacro:property name="wheel_zoff" value="0.2" />
  <!-- Position the wheels along the x-axis -->
  <xacro:property name="wheel_xoff" value="0.221" />

  <!-- Position the caster wheel along the x-axis -->
  <xacro:property name="caster_xoff" value="-0.40" />

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}" />
      <mass value="${m}" />
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}"
        iyz="0.0" izz="${(m/12) * (w*w + h*h)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}" />
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12) * (3*r*r + h*h)}"
        iyz="0" izz="${(m/2) * (r*r)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0"
        izz="${(2/5) * m * (r*r)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="entity_material" params="color alpha">
    <material name="black">
      <color rgba="0.0 0.0 0.0 1.0" />
    </material>
  </xacro:macro>

  <!-- <geometry name="wheel_stl">
    <mesh filename="package://nav2_sample/meshes/wheel.STL" scale="${27/29} ${27/29} ${27/29}"/>
  </geometry> -->

  <!-- *********************** DRIVE WHEELS ******************************  -->

  <xacro:macro name="wheel" params="prefix x_reflect y_reflect wheel_radius wheel_width wheel_xoff wheel_zoff">
    <link name="${prefix}_link">
      <visual>
        <!-- <origin xyz="${wheel_radius} ${wheel_radius/0.29 * -0.05} ${-wheel_radius}" rpy="0 0 0" /> -->
        <origin xyz="${y_reflect * wheel_radius} ${ y_reflect * wheel_radius/0.29 * - 0.05} ${-wheel_radius}" rpy="0 0 ${y_reflect * pi/2}" />
        <geometry>
          <mesh filename="package://nav2_sample/meshes/wheel.STL" scale="${wheel_radius/0.29} ${wheel_radius/0.29} ${wheel_radius/0.29}"/>
        </geometry>
        <material name="light_black" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="110.5" r="${wheel_radius}" h="${wheel_width}" />

    </link>

    <!-- Connect the wheels to the base_link at the appropriate location, and 
       define a continuous joint to allow the wheels to freely rotate about
       an axis -->
    <joint name="${prefix}_joint" type="revolute">
      <parent link="base_link" />
      <child link="${prefix}_link" />
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}"
        rpy="0 0 0" />
      <limit upper="3.1415" lower="-3.1415" effort="30" velocity="5.0" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <!-- Init colour -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0" />
  </material>

  <material name="dark">
    <color rgba="0.3 0.3 0.3 1.0" />
  </material>

  <material name="light_black">
    <color rgba="0.7 0.7 0.7 1.0" />
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0" />
  </material>

  <material name="light_blue">
    <color rgba="${0/255} ${0/255} ${255/255} 0.5" />
  </material>

  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0" />
  </material>

  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0" />
  </material>

  <material name="orange">
    <color rgba="1.0 0.4235 0.0392 1.0" />
  </material>

  <material name="brown">
    <color rgba="0.8706 0.8118 0.7647 1.0" />
  </material>

  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0" />
  </material>

  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0" />
  </material>


</robot>